### ISSUE TITLE
pragma package is not supported anymore

### ISSUE THREAD

**Issue by timwolfram1994** [dariober/quadratic-programming-deconvolution#1]
Hi, while I am trying to apply the tutorial I get the message that "pragma" is not available anymore.
I think its not too much of a hustle to transfer the knowledge to a common regression package, but
I find this tutorial very useful and it might be worth being kept updated.

**Comment by dariober** [comment]
Hi- Thanks for your interest! [pracma](https://cran.r-project.org/web/packages/pracma/index.html) (check spelling) is still available. However, I noticed that [quadprog](https://cran.r-project.org/web/packages/quadprog/index.html) is no longer installed together with pracma so I edited my tutorial to include `install.packages('quadprog')`. I'm closing the issue now but feel free to reopen.
